### ISSUE TITLE
What files used in analysis, and are these fully up to date?

### ISSUE THREAD

**Issue by ligon** [DRU001/Project-4---ENVECON-153#1]
If the README.md file had a markdown link to the file(s) actually used in analysis that would be helpful.  

And a question: at the moment, the most recent updates to these files happened five days ago.  Is that really the latest?  Perhaps a "git push" is called for?

**Comment by nathanorwig** [comment]
The Project 4 File is the only one needed in analysis. Nothing has changed in terms of coding in last five days so it is up to  date.
