### ISSUE TITLE
Why are these Files relevant?

### ISSUE THREAD

**Issue by andrawis97** [DRU001/Project-4---ENVECON-153#2]

**Comment by andrawis97** [comment]
There are lots of notebooks like [example](Final-Notebook-3.ipynb) that dont belong to the project, was wondering if that connected to other notebooks?

**Comment by nathanorwig** [comment]
I think I removed most of the extra ones that weren't necessary. There are still many CSVs that were used at some point to analyze a feature but will try to make it cleaner for future projects.
