### ISSUE TITLE
File Organization

### ISSUE THREAD

**Issue by clairevparkinson** [DRU001/Project-4---ENVECON-153#3]
The file organization in your project 4 repository is a bit messy and confusing. I would recommend making separate folders for the different projects and their corresponding data sets.

**Comment by clairevparkinson** [comment]
The Project 3 file has incorrect labeling within the notebook (information on my former group's project 2). This information should be updated or removed.

**Comment by nathanorwig** [comment]
I deleted some of the extra files but had issues in terms of grouping the CSV and .py files and creating the correct path to them. Keeping them in the main folder is easiest in terms of quickly grabbing them for code but in future I should try to make paths so that grouped files work.

**Comment by nathanorwig** [comment]
I moved CSVs, the py files are much harder and didn't seem necessary to put in folder but should be at least somewhat clearer now hopefully.
