### ISSUE TITLE
Nutrition thresholds

### ISSUE THREAD

**Issue by tsitu97** [DRU001/Project-4---ENVECON-153#5]
Name "b" is not defined
This continues popping up afterwards

**Comment by nathanorwig** [comment]
Where exactly in the code are you?

**Comment by tsitu97** [comment]
The first step! I'm getting redirected to an error where "No module named 'ndb'"

**Comment by jnuesca** [comment]
I'm having the same issue. 
<img width="991" alt="Messages Image(4103143521)" src="https://user-images.githubusercontent.com/24834103/57048763-2cf21680-6c2a-11e9-8a0d-0043f865410e.png">
